name: pytorch_cpuonly
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cpuonly
  - matplotlib
  - tensorboard
  - pyyaml
  - pandas
  - pytorch-lightning
  - wandb
  - pip
  - pip:
    - -r requirements.txt
