name: pytorch_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.4
  - pytorch
  - torchvision
  - albumentations
  - matplotlib
  - tensorboard
  - pyyaml
  - pandas
  - numpy
  - pillow
  - opencv
  # - pip
  # - pip:
  #   - opencv-python