name: pytorch_env
channels:
  - pytorch # for pytorch and torchvision.
  - conda-forge
dependencies:
  - python>=3.8
  - anaconda
  - conda
  - pandas=1.5.3
  - PyYAML==6.0
  - matplotlib==3.6.3
  - pip
  - pip: 
    - -r requirements.txt
