name: pytorch-env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python>=3.5
  - anaconda
  - pytorch=1.13.1
  - albumentations=1.3.0
  - torchvision=0.14.1
  - pandas=1.5.3
  - PyYAML==6.0
  - matplotlib==3.6.3
  - numpy==1.24.2
  - opencv_python==4.7.0.68
  # - pip: 
  #   - -r requirements.txt
