name: pytorch_env
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - matplotlib
  - pyyaml
  - pandas
  - wandb
  - pytest
  - pip
  - pip:
    - -r requirements.txt
