experiment:
  preprocessing: SLOPE
  name: ResNet50 Transfer Learning on Faster R-CNN
  description: ---
  tags:
   - SLOPE

classes:
  dataset: 
    name: Dataset2022
    package: data
    module: datasets
  logger: 
    name: WandbLogger
    package: loggers
    module: wandb

data:
  dir: replication/data
  batch_size: 10
  num_workers: 4
  transform_opts: 
    width: 224
    height: 224

training:
  epochs: 1
  optimizer:    
    type: sdg
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005
  scheduler: 
    type: steplr
    step_size: 30
    gamma: 0.1