name: REPLICATION
dataset:
  type: PascalVOCDataset
  path: ./datasets/slope
  loader:
    num_workers: 4
    batch_size: 10
  transform: 
    width: 224
    height: 224

trainer:
  epochs: 120
  
  optimizer: 
    name: SDG
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005
  scheduler:
    step_size: 30
    gamma: 0.1

test:
  epochs: 120

model:
  classes: 2 # one class for the background and one for burial mounds
  path: ./models/replication/
  name: "Slope_RGB_Fixed_Val_Add_Augm"

