experiment:
  project: ResNet50TransferLearningFasterR-CNN
  name: SLOPE
  description: ResNet50 Transfer Learning on Faster R-CNN
  tags:
   - SLOPE

classes:
  dataset: 
    name: PascalVOCDataset
    package: data
    module: datasets
  logger: 
    name: WandbLogger
    package: loggers
    module: wandb

model:
  checkpoint_dir: checkpoints/slope

data:
  train_dirs:
    - datasets/processed/NDH_Ostfold_5pkt_2015/fredrikstad_sarpsborg/slope
    - datasets/processed/NDH_Steinkjer_5pkt_2017/steinkjer/slope
    - datasets/processed/NDH_Larvik_5pkt_2017/larvik_kaupang/slope
  val_dirs:
    - datasets/processed/NDH_Ostfold_5pkt_2015/moss_naerum/slope    
    - datasets/processed/NDH_Rogaland_5pkt_2016/klepp/slope
    - datasets/processed/NDH_Stange_5pkt_2016/stange/slope
  test_dirs: 
    - datasets/processed/NDH_Karmoy_Haugesund_5pkt_2017/avaldsnes/slope
    - datasets/processed/NDH_Larvik_5pkt_2017/larvik_hedrum/slope

dataloader:
  batch_size: 10
  num_workers: 4
  transform_opts: 
    width: 224
    height: 224

training:
  seed: 1
  epochs: 10
  optimizer:    
    type: sdg
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
  scheduler: 
    type: steplr
    step_size: 30
    gamma: 0.1