experiment:
  description: Replication
  name: SLRM
  project: Replication
  tags:
  - SLRM

classes:
  dataset: 
    name: Dataset2022
    package: data
    module: datasets
  logger: 
    name: WandbLogger
    package: loggers
    module: wandb

model:
  checkpoint_dir: replication/checkpoints/SLRM

data:
  train_dirs:
    - replication/datasets/SLRM_RGB_Fixed_Val_Augmentation/train
  val_dirs:
    - replication/datasets/SLRM_RGB_Fixed_Val_Augmentation/val
  test_dirs: 
    - replication/datasets/SLRM_RGB_Fixed_Val_Augmentation/test

dataloader:
  batch_size: 10
  num_workers: 4
  transform_opts:
    height: 224
    width: 224
    mean: 
      - 0.485
      - 0.456
      - 0.406
    std:
      - 0.229
      - 0.224
      - 0.225
model:
  save_checkpoints: False
  checkpoint_dir: checkpoints/SLRM
training:
  epochs: 1
  optimizer:
    lr: 0.005
    momentum: 0.9
    type: sdg
    weight_decay: 0.0005
  scheduler:
    gamma: 0.1
    step_size: 30
    type: steplr
  seed: 1
