experiment:
  description: Troubleshooting - preprocessing
  name: SLOPE
  project: Troubleshooting
  tags:
  - SLOPE

classes:
  dataset: 
    name: Dataset2022
    package: data
    module: datasets
  logger: 
    name: WandbLogger
    package: loggers
    module: wandb

model:
  checkpoint_dir: troubleshoot/checkpoints/SLOPE

data:
  train_dirs:
    - datasets/processed_v2/NDH_Larvik_5pkt_2017/kaupang
  val_dirs:
    - datasets/processed_v2/NDH_Larvik_5pkt_2017/larvik
  test_dirs: 
    - datasets/processed_v2/NDH_Karmoy_Haugesund/avaldsnes

dataloader:
  batch_size: 10
  num_workers: 4
  transform_opts:
    height: 224
    width: 224
    # mean: 
    #   - 0.485
    #   - 0.456
    #   - 0.406
    # std:
    #   - 0.229
    #   - 0.224
    #   - 0.225
training:
  epochs: 1
  optimizer:
    lr: 0.005
    momentum: 0.9
    type: sdg
    weight_decay: 0.0005
  scheduler:
    gamma: 0.1
    step_size: 30
    type: steplr
  seed: 1
